baseurl = "/"
title = "Ikram GRYACH - Portfolio"
theme = "hugo-creative-portfolio-theme"
languageCode = "fr-fr"

[params]
  style = "default"
  description = "Portfolio professionnel d'Ikram GRYACH - Étudiante en Cybersécurité"
  copyright = "&copy;2024 Ikram GRYACH"
  sidebarAbout = [
    "Étudiante en 1ère année du cycle d'ingénieur en cybersécurité et confiance numérique à l'INPT",
    "Passionnée par la cybersécurité et la confiance numérique",
    "À la recherche d'un stage de fin d'année"
  ]
  email = "ikramgryachlinkedin@gmail.com"
  custom_css = ["css/custom.css"]

  [[params.navlinks]]
  name = "Projets"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "À propos"
  url = "/about/"

  [[params.navlinks]]
  name = "Contact"
  url = "/contact/"

  [params.social]
  email = "ikramgryachlinkedin@gmail.com"
  linkedin = "linkedin.com/in/IKRAM-GRYACH"
  phone = "06 58 61 55 11" 